// Auto-generated by scripts/extract-palettes.mjs.
// Source: https://github.com/posit-dev/ggsql/tree/main/doc/syntax/scale/aesthetic/examples
// Do not edit by hand — re-run the script and commit the result.

export const DEFAULT_DISCRETE = "ggsql10";
export const DEFAULT_CONTINUOUS = "sequential";

interface DiscretePalette {
  name: string;
  colors: string[];
}

export type ContinuousCategory = "sequential" | "diverging" | "multi" | "cyclic";

interface ContinuousPalette {
  name: string;
  category: ContinuousCategory;
  stops: Array<{ offset: number; color: string }>;
}

export const DISCRETE_PALETTES: DiscretePalette[] = [
  {
    "name": "ggsql10",
    "colors": [
      "#0067A5",
      "#F38400",
      "#008856",
      "#F3C300",
      "#875692",
      "#A1CAF1",
      "#BE0032",
      "#8DB600",
      "#654522",
      "#E68FAC"
    ]
  },
  {
    "name": "tableau10",
    "colors": [
      "#4e79a7",
      "#f28e2b",
      "#e15759",
      "#76b7b2",
      "#59a14f",
      "#edc948",
      "#b07aa1",
      "#ff9da7",
      "#9c755f",
      "#bab0ac"
    ]
  },
  {
    "name": "category10",
    "colors": [
      "#1f77b4",
      "#ff7f0e",
      "#2ca02c",
      "#d62728",
      "#9467bd",
      "#8c564b",
      "#e377c2",
      "#7f7f7f",
      "#bcbd22",
      "#17becf"
    ]
  },
  {
    "name": "set1",
    "colors": [
      "#e41a1c",
      "#377eb8",
      "#4daf4a",
      "#984ea3",
      "#ff7f00",
      "#ffff33",
      "#a65628",
      "#f781bf",
      "#999999"
    ]
  },
  {
    "name": "set2",
    "colors": [
      "#66c2a5",
      "#fc8d62",
      "#8da0cb",
      "#e78ac3",
      "#a6d854",
      "#ffd92f",
      "#e5c494",
      "#b3b3b3"
    ]
  },
  {
    "name": "set3",
    "colors": [
      "#8dd3c7",
      "#ffffb3",
      "#bebada",
      "#fb8072",
      "#80b1d3",
      "#fdb462",
      "#b3de69",
      "#fccde5",
      "#d9d9d9",
      "#bc80bd",
      "#ccebc5",
      "#ffed6f"
    ]
  },
  {
    "name": "pastel1",
    "colors": [
      "#fbb4ae",
      "#b3cde3",
      "#ccebc5",
      "#decbe4",
      "#fed9a6",
      "#ffffcc",
      "#e5d8bd",
      "#fddaec",
      "#f2f2f2"
    ]
  },
  {
    "name": "pastel2",
    "colors": [
      "#b3e2cd",
      "#fdcdac",
      "#cbd5e8",
      "#f4cae4",
      "#e6f5c9",
      "#fff2ae",
      "#f1e2cc",
      "#cccccc"
    ]
  },
  {
    "name": "dark2",
    "colors": [
      "#1b9e77",
      "#d95f02",
      "#7570b3",
      "#e7298a",
      "#66a61e",
      "#e6ab02",
      "#a6761d",
      "#666666"
    ]
  },
  {
    "name": "paired",
    "colors": [
      "#a6cee3",
      "#1f78b4",
      "#b2df8a",
      "#33a02c",
      "#fb9a99",
      "#e31a1c",
      "#fdbf6f",
      "#ff7f00",
      "#cab2d6",
      "#6a3d9a",
      "#ffff99",
      "#b15928"
    ]
  },
  {
    "name": "accent",
    "colors": [
      "#7fc97f",
      "#beaed4",
      "#fdc086",
      "#ffff99",
      "#386cb0",
      "#f0027f",
      "#bf5b17",
      "#666666"
    ]
  },
  {
    "name": "kelly22",
    "colors": [
      "#F3C300",
      "#875692",
      "#F38400",
      "#A1CAF1",
      "#BE0032",
      "#C2B280",
      "#848482",
      "#008856",
      "#E68FAC",
      "#0067A5",
      "#F99379",
      "#604E97",
      "#F6A600",
      "#B3446C",
      "#DCD300",
      "#882D17",
      "#8DB600",
      "#654522",
      "#E25822",
      "#2B3D26"
    ]
  }
];

export const CONTINUOUS_PALETTES: ContinuousPalette[] = [
  {
    "name": "sequential",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#021326"
      },
      {
        "offset": 5.3,
        "color": "#051F3B"
      },
      {
        "offset": 10.5,
        "color": "#062B50"
      },
      {
        "offset": 15.8,
        "color": "#063966"
      },
      {
        "offset": 21.1,
        "color": "#0B4679"
      },
      {
        "offset": 26.3,
        "color": "#125286"
      },
      {
        "offset": 31.6,
        "color": "#1A5F8E"
      },
      {
        "offset": 36.8,
        "color": "#216B91"
      },
      {
        "offset": 42.1,
        "color": "#27728E"
      },
      {
        "offset": 47.4,
        "color": "#2E798B"
      },
      {
        "offset": 52.6,
        "color": "#347F87"
      },
      {
        "offset": 57.9,
        "color": "#3A8584"
      },
      {
        "offset": 63.2,
        "color": "#408A7F"
      },
      {
        "offset": 68.4,
        "color": "#48917A"
      },
      {
        "offset": 73.7,
        "color": "#519976"
      },
      {
        "offset": 78.9,
        "color": "#59A071"
      },
      {
        "offset": 84.2,
        "color": "#66AC6C"
      },
      {
        "offset": 89.5,
        "color": "#76B767"
      },
      {
        "offset": 94.7,
        "color": "#88C36A"
      },
      {
        "offset": 100,
        "color": "#A4D176"
      }
    ]
  },
  {
    "name": "acton",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#260C3F"
      },
      {
        "offset": 5.3,
        "color": "#321D4D"
      },
      {
        "offset": 10.5,
        "color": "#3D2C5D"
      },
      {
        "offset": 15.8,
        "color": "#463B6A"
      },
      {
        "offset": 21.1,
        "color": "#514A78"
      },
      {
        "offset": 26.3,
        "color": "#5B5783"
      },
      {
        "offset": 31.6,
        "color": "#6C5F8C"
      },
      {
        "offset": 36.8,
        "color": "#7A638C"
      },
      {
        "offset": 42.1,
        "color": "#8B648D"
      },
      {
        "offset": 47.4,
        "color": "#9E658E"
      },
      {
        "offset": 52.6,
        "color": "#B16690"
      },
      {
        "offset": 57.9,
        "color": "#C56C94"
      },
      {
        "offset": 63.2,
        "color": "#D0799F"
      },
      {
        "offset": 68.4,
        "color": "#D68BAE"
      },
      {
        "offset": 73.7,
        "color": "#DC9DBE"
      },
      {
        "offset": 78.9,
        "color": "#E0ADCC"
      },
      {
        "offset": 84.2,
        "color": "#E5BFD9"
      },
      {
        "offset": 89.5,
        "color": "#E9CEE5"
      },
      {
        "offset": 94.7,
        "color": "#ECDEF0"
      },
      {
        "offset": 100,
        "color": "#F0EAF9"
      }
    ]
  },
  {
    "name": "bamako",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#003A46"
      },
      {
        "offset": 5.3,
        "color": "#063F44"
      },
      {
        "offset": 10.5,
        "color": "#0C433F"
      },
      {
        "offset": 15.8,
        "color": "#13473A"
      },
      {
        "offset": 21.1,
        "color": "#1D4C34"
      },
      {
        "offset": 26.3,
        "color": "#26532E"
      },
      {
        "offset": 31.6,
        "color": "#335A27"
      },
      {
        "offset": 36.8,
        "color": "#3F6320"
      },
      {
        "offset": 42.1,
        "color": "#4C6B18"
      },
      {
        "offset": 47.4,
        "color": "#5A740E"
      },
      {
        "offset": 52.6,
        "color": "#687E06"
      },
      {
        "offset": 57.9,
        "color": "#7A8500"
      },
      {
        "offset": 63.2,
        "color": "#8C8A00"
      },
      {
        "offset": 68.4,
        "color": "#9D9006"
      },
      {
        "offset": 73.7,
        "color": "#B09D1D"
      },
      {
        "offset": 78.9,
        "color": "#C1AB33"
      },
      {
        "offset": 84.2,
        "color": "#D3BA51"
      },
      {
        "offset": 89.5,
        "color": "#E3C970"
      },
      {
        "offset": 94.7,
        "color": "#F2D891"
      },
      {
        "offset": 100,
        "color": "#FFE5AC"
      }
    ]
  },
  {
    "name": "batlow",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#001959"
      },
      {
        "offset": 5.3,
        "color": "#0B2C5D"
      },
      {
        "offset": 10.5,
        "color": "#103E5F"
      },
      {
        "offset": 15.8,
        "color": "#134B60"
      },
      {
        "offset": 21.1,
        "color": "#195761"
      },
      {
        "offset": 26.3,
        "color": "#25615F"
      },
      {
        "offset": 31.6,
        "color": "#376B58"
      },
      {
        "offset": 36.8,
        "color": "#4A724D"
      },
      {
        "offset": 42.1,
        "color": "#5F7843"
      },
      {
        "offset": 47.4,
        "color": "#767F37"
      },
      {
        "offset": 52.6,
        "color": "#8D852D"
      },
      {
        "offset": 57.9,
        "color": "#A98C2C"
      },
      {
        "offset": 63.2,
        "color": "#C19037"
      },
      {
        "offset": 68.4,
        "color": "#D8944A"
      },
      {
        "offset": 73.7,
        "color": "#ED9A64"
      },
      {
        "offset": 78.9,
        "color": "#F8A381"
      },
      {
        "offset": 84.2,
        "color": "#FDADA1"
      },
      {
        "offset": 89.5,
        "color": "#FDB7BE"
      },
      {
        "offset": 94.7,
        "color": "#FCC1DC"
      },
      {
        "offset": 100,
        "color": "#F9CCF9"
      }
    ]
  },
  {
    "name": "batlowk",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#04050A"
      },
      {
        "offset": 5.3,
        "color": "#101722"
      },
      {
        "offset": 10.5,
        "color": "#192B3F"
      },
      {
        "offset": 15.8,
        "color": "#253E53"
      },
      {
        "offset": 21.1,
        "color": "#33505E"
      },
      {
        "offset": 26.3,
        "color": "#3F5A5E"
      },
      {
        "offset": 31.6,
        "color": "#4B6359"
      },
      {
        "offset": 36.8,
        "color": "#586B52"
      },
      {
        "offset": 42.1,
        "color": "#667348"
      },
      {
        "offset": 47.4,
        "color": "#7A7E3F"
      },
      {
        "offset": 52.6,
        "color": "#918739"
      },
      {
        "offset": 57.9,
        "color": "#AC9239"
      },
      {
        "offset": 63.2,
        "color": "#C79943"
      },
      {
        "offset": 68.4,
        "color": "#DE9F57"
      },
      {
        "offset": 73.7,
        "color": "#EEA572"
      },
      {
        "offset": 78.9,
        "color": "#F7AB8C"
      },
      {
        "offset": 84.2,
        "color": "#FCB2A7"
      },
      {
        "offset": 89.5,
        "color": "#FDB8C0"
      },
      {
        "offset": 94.7,
        "color": "#FDC3DE"
      },
      {
        "offset": 100,
        "color": "#F9CCF9"
      }
    ]
  },
  {
    "name": "batloww",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#001959"
      },
      {
        "offset": 5.3,
        "color": "#0B2C5D"
      },
      {
        "offset": 10.5,
        "color": "#103E5F"
      },
      {
        "offset": 15.8,
        "color": "#134A60"
      },
      {
        "offset": 21.1,
        "color": "#195761"
      },
      {
        "offset": 26.3,
        "color": "#226060"
      },
      {
        "offset": 31.6,
        "color": "#336B5A"
      },
      {
        "offset": 36.8,
        "color": "#467252"
      },
      {
        "offset": 42.1,
        "color": "#5A7A47"
      },
      {
        "offset": 47.4,
        "color": "#72833D"
      },
      {
        "offset": 52.6,
        "color": "#8A8B33"
      },
      {
        "offset": 57.9,
        "color": "#A69434"
      },
      {
        "offset": 63.2,
        "color": "#C09E47"
      },
      {
        "offset": 68.4,
        "color": "#D4A561"
      },
      {
        "offset": 73.7,
        "color": "#E5AA7E"
      },
      {
        "offset": 78.9,
        "color": "#F0B198"
      },
      {
        "offset": 84.2,
        "color": "#F9C3B9"
      },
      {
        "offset": 89.5,
        "color": "#FFD9D8"
      },
      {
        "offset": 94.7,
        "color": "#FFEEED"
      },
      {
        "offset": 100,
        "color": "#FFFEFE"
      }
    ]
  },
  {
    "name": "bilbao",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#4C0000"
      },
      {
        "offset": 5.3,
        "color": "#5F1315"
      },
      {
        "offset": 10.5,
        "color": "#722227"
      },
      {
        "offset": 15.8,
        "color": "#813239"
      },
      {
        "offset": 21.1,
        "color": "#914148"
      },
      {
        "offset": 26.3,
        "color": "#995152"
      },
      {
        "offset": 31.6,
        "color": "#9F5E55"
      },
      {
        "offset": 36.8,
        "color": "#A16859"
      },
      {
        "offset": 42.1,
        "color": "#A5725A"
      },
      {
        "offset": 47.4,
        "color": "#A77D5D"
      },
      {
        "offset": 52.6,
        "color": "#AA855F"
      },
      {
        "offset": 57.9,
        "color": "#AC9161"
      },
      {
        "offset": 63.2,
        "color": "#B19D67"
      },
      {
        "offset": 68.4,
        "color": "#B7AB79"
      },
      {
        "offset": 73.7,
        "color": "#BEB692"
      },
      {
        "offset": 78.9,
        "color": "#C3BEA6"
      },
      {
        "offset": 84.2,
        "color": "#C9C6BB"
      },
      {
        "offset": 89.5,
        "color": "#D3D2CE"
      },
      {
        "offset": 94.7,
        "color": "#E7E7E7"
      },
      {
        "offset": 100,
        "color": "#FFFFFF"
      }
    ]
  },
  {
    "name": "buda",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#B200B2"
      },
      {
        "offset": 5.3,
        "color": "#B218A7"
      },
      {
        "offset": 10.5,
        "color": "#B2289F"
      },
      {
        "offset": 15.8,
        "color": "#B43798"
      },
      {
        "offset": 21.1,
        "color": "#B84592"
      },
      {
        "offset": 26.3,
        "color": "#BB518E"
      },
      {
        "offset": 31.6,
        "color": "#C05D8B"
      },
      {
        "offset": 36.8,
        "color": "#C46886"
      },
      {
        "offset": 42.1,
        "color": "#C77284"
      },
      {
        "offset": 47.4,
        "color": "#CC7F7F"
      },
      {
        "offset": 52.6,
        "color": "#CE8A7D"
      },
      {
        "offset": 57.9,
        "color": "#D29779"
      },
      {
        "offset": 63.2,
        "color": "#D4A177"
      },
      {
        "offset": 68.4,
        "color": "#D8AC73"
      },
      {
        "offset": 73.7,
        "color": "#DAB971"
      },
      {
        "offset": 78.9,
        "color": "#DEC56D"
      },
      {
        "offset": 84.2,
        "color": "#E0D26B"
      },
      {
        "offset": 89.5,
        "color": "#E5DF67"
      },
      {
        "offset": 94.7,
        "color": "#F0EE66"
      },
      {
        "offset": 100,
        "color": "#FFFF66"
      }
    ]
  },
  {
    "name": "davos",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#00054A"
      },
      {
        "offset": 5.3,
        "color": "#06185D"
      },
      {
        "offset": 10.5,
        "color": "#112B70"
      },
      {
        "offset": 15.8,
        "color": "#193B7F"
      },
      {
        "offset": 21.1,
        "color": "#264D8E"
      },
      {
        "offset": 26.3,
        "color": "#325E98"
      },
      {
        "offset": 31.6,
        "color": "#3F6C9D"
      },
      {
        "offset": 36.8,
        "color": "#4C779D"
      },
      {
        "offset": 42.1,
        "color": "#588099"
      },
      {
        "offset": 47.4,
        "color": "#658A94"
      },
      {
        "offset": 52.6,
        "color": "#729190"
      },
      {
        "offset": 57.9,
        "color": "#7F998B"
      },
      {
        "offset": 63.2,
        "color": "#8CA487"
      },
      {
        "offset": 68.4,
        "color": "#9EB187"
      },
      {
        "offset": 73.7,
        "color": "#B6C391"
      },
      {
        "offset": 78.9,
        "color": "#CED6A1"
      },
      {
        "offset": 84.2,
        "color": "#E5E9BB"
      },
      {
        "offset": 89.5,
        "color": "#F2F3D3"
      },
      {
        "offset": 94.7,
        "color": "#FAFAEB"
      },
      {
        "offset": 100,
        "color": "#FEFEFE"
      }
    ]
  },
  {
    "name": "devon",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#2C194C"
      },
      {
        "offset": 5.3,
        "color": "#2B2658"
      },
      {
        "offset": 10.5,
        "color": "#283366"
      },
      {
        "offset": 15.8,
        "color": "#273F72"
      },
      {
        "offset": 21.1,
        "color": "#264D81"
      },
      {
        "offset": 26.3,
        "color": "#2A5A92"
      },
      {
        "offset": 31.6,
        "color": "#3266A6"
      },
      {
        "offset": 36.8,
        "color": "#3F70B8"
      },
      {
        "offset": 42.1,
        "color": "#547BCA"
      },
      {
        "offset": 47.4,
        "color": "#7187D8"
      },
      {
        "offset": 52.6,
        "color": "#8A93E0"
      },
      {
        "offset": 57.9,
        "color": "#A19FEA"
      },
      {
        "offset": 63.2,
        "color": "#B1ACEE"
      },
      {
        "offset": 68.4,
        "color": "#BDB7F1"
      },
      {
        "offset": 73.7,
        "color": "#C7C3F3"
      },
      {
        "offset": 78.9,
        "color": "#D2CDF6"
      },
      {
        "offset": 84.2,
        "color": "#DEDAF8"
      },
      {
        "offset": 89.5,
        "color": "#E7E5F9"
      },
      {
        "offset": 94.7,
        "color": "#F3F2FD"
      },
      {
        "offset": 100,
        "color": "#FFFFFF"
      }
    ]
  },
  {
    "name": "glasgow",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#351338"
      },
      {
        "offset": 5.3,
        "color": "#41152D"
      },
      {
        "offset": 10.5,
        "color": "#4D1924"
      },
      {
        "offset": 15.8,
        "color": "#591D19"
      },
      {
        "offset": 21.1,
        "color": "#67240D"
      },
      {
        "offset": 26.3,
        "color": "#723104"
      },
      {
        "offset": 31.6,
        "color": "#744000"
      },
      {
        "offset": 36.8,
        "color": "#734E00"
      },
      {
        "offset": 42.1,
        "color": "#725B07"
      },
      {
        "offset": 47.4,
        "color": "#6E6A1F"
      },
      {
        "offset": 52.6,
        "color": "#6B7438"
      },
      {
        "offset": 57.9,
        "color": "#668052"
      },
      {
        "offset": 63.2,
        "color": "#618B6C"
      },
      {
        "offset": 68.4,
        "color": "#5F9485"
      },
      {
        "offset": 73.7,
        "color": "#669F9F"
      },
      {
        "offset": 78.9,
        "color": "#79ABB4"
      },
      {
        "offset": 84.2,
        "color": "#92B6C9"
      },
      {
        "offset": 89.5,
        "color": "#A7BFD9"
      },
      {
        "offset": 94.7,
        "color": "#BFC7EB"
      },
      {
        "offset": 100,
        "color": "#DAD2FF"
      }
    ]
  },
  {
    "name": "grayc",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#000000"
      },
      {
        "offset": 5.3,
        "color": "#131313"
      },
      {
        "offset": 10.5,
        "color": "#212121"
      },
      {
        "offset": 15.8,
        "color": "#2D2D2D"
      },
      {
        "offset": 21.1,
        "color": "#3A3A3A"
      },
      {
        "offset": 26.3,
        "color": "#464646"
      },
      {
        "offset": 31.6,
        "color": "#525252"
      },
      {
        "offset": 36.8,
        "color": "#5D5D5D"
      },
      {
        "offset": 42.1,
        "color": "#666666"
      },
      {
        "offset": 47.4,
        "color": "#727272"
      },
      {
        "offset": 52.6,
        "color": "#7B7B7B"
      },
      {
        "offset": 57.9,
        "color": "#868686"
      },
      {
        "offset": 63.2,
        "color": "#929292"
      },
      {
        "offset": 68.4,
        "color": "#9E9E9E"
      },
      {
        "offset": 73.7,
        "color": "#ACACAC"
      },
      {
        "offset": 78.9,
        "color": "#B8B8B8"
      },
      {
        "offset": 84.2,
        "color": "#CACACA"
      },
      {
        "offset": 89.5,
        "color": "#D9D9D9"
      },
      {
        "offset": 94.7,
        "color": "#EBEBEB"
      },
      {
        "offset": 100,
        "color": "#FFFFFF"
      }
    ]
  },
  {
    "name": "hawaii",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#8C0172"
      },
      {
        "offset": 5.3,
        "color": "#8E1966"
      },
      {
        "offset": 10.5,
        "color": "#922859"
      },
      {
        "offset": 15.8,
        "color": "#92354E"
      },
      {
        "offset": 21.1,
        "color": "#944445"
      },
      {
        "offset": 26.3,
        "color": "#97513B"
      },
      {
        "offset": 31.6,
        "color": "#995F32"
      },
      {
        "offset": 36.8,
        "color": "#9A6C2A"
      },
      {
        "offset": 42.1,
        "color": "#9B7A20"
      },
      {
        "offset": 47.4,
        "color": "#9D8C1B"
      },
      {
        "offset": 52.6,
        "color": "#999F1F"
      },
      {
        "offset": 57.9,
        "color": "#92B033"
      },
      {
        "offset": 63.2,
        "color": "#87BE4C"
      },
      {
        "offset": 68.4,
        "color": "#7BC766"
      },
      {
        "offset": 73.7,
        "color": "#6ED285"
      },
      {
        "offset": 78.9,
        "color": "#64D9A1"
      },
      {
        "offset": 84.2,
        "color": "#5FE4C1"
      },
      {
        "offset": 89.5,
        "color": "#6CEBDC"
      },
      {
        "offset": 94.7,
        "color": "#8EF0F1"
      },
      {
        "offset": 100,
        "color": "#B2F2FD"
      }
    ]
  },
  {
    "name": "imola",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#1933B2"
      },
      {
        "offset": 5.3,
        "color": "#1F3BAD"
      },
      {
        "offset": 10.5,
        "color": "#2446A9"
      },
      {
        "offset": 15.8,
        "color": "#274DA5"
      },
      {
        "offset": 21.1,
        "color": "#2C579F"
      },
      {
        "offset": 26.3,
        "color": "#315F9B"
      },
      {
        "offset": 31.6,
        "color": "#376796"
      },
      {
        "offset": 36.8,
        "color": "#3E708E"
      },
      {
        "offset": 42.1,
        "color": "#457787"
      },
      {
        "offset": 47.4,
        "color": "#4D8080"
      },
      {
        "offset": 52.6,
        "color": "#598B7D"
      },
      {
        "offset": 57.9,
        "color": "#669879"
      },
      {
        "offset": 63.2,
        "color": "#72A576"
      },
      {
        "offset": 68.4,
        "color": "#7FB272"
      },
      {
        "offset": 73.7,
        "color": "#8CBF70"
      },
      {
        "offset": 78.9,
        "color": "#9BCD6C"
      },
      {
        "offset": 84.2,
        "color": "#AEDE68"
      },
      {
        "offset": 89.5,
        "color": "#C5EB66"
      },
      {
        "offset": 94.7,
        "color": "#E4F666"
      },
      {
        "offset": 100,
        "color": "#FFFF66"
      }
    ]
  },
  {
    "name": "lajolla",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#191900"
      },
      {
        "offset": 5.3,
        "color": "#241D06"
      },
      {
        "offset": 10.5,
        "color": "#32210E"
      },
      {
        "offset": 15.8,
        "color": "#402615"
      },
      {
        "offset": 21.1,
        "color": "#552D20"
      },
      {
        "offset": 26.3,
        "color": "#6C352C"
      },
      {
        "offset": 31.6,
        "color": "#863E39"
      },
      {
        "offset": 36.8,
        "color": "#A14543"
      },
      {
        "offset": 42.1,
        "color": "#BB4C48"
      },
      {
        "offset": 47.4,
        "color": "#D2584C"
      },
      {
        "offset": 52.6,
        "color": "#DD674D"
      },
      {
        "offset": 57.9,
        "color": "#E17950"
      },
      {
        "offset": 63.2,
        "color": "#E58851"
      },
      {
        "offset": 68.4,
        "color": "#E79852"
      },
      {
        "offset": 73.7,
        "color": "#EBA952"
      },
      {
        "offset": 78.9,
        "color": "#EEB855"
      },
      {
        "offset": 84.2,
        "color": "#F3CC60"
      },
      {
        "offset": 89.5,
        "color": "#F8DF7F"
      },
      {
        "offset": 94.7,
        "color": "#FDF2A7"
      },
      {
        "offset": 100,
        "color": "#FFFECB"
      }
    ]
  },
  {
    "name": "lapaz",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#190C64"
      },
      {
        "offset": 5.3,
        "color": "#1F1D6E"
      },
      {
        "offset": 10.5,
        "color": "#212C79"
      },
      {
        "offset": 15.8,
        "color": "#263984"
      },
      {
        "offset": 21.1,
        "color": "#28488C"
      },
      {
        "offset": 26.3,
        "color": "#2D5594"
      },
      {
        "offset": 31.6,
        "color": "#33639A"
      },
      {
        "offset": 36.8,
        "color": "#3B709F"
      },
      {
        "offset": 42.1,
        "color": "#467AA3"
      },
      {
        "offset": 47.4,
        "color": "#5386A4"
      },
      {
        "offset": 52.6,
        "color": "#6390A1"
      },
      {
        "offset": 57.9,
        "color": "#76999F"
      },
      {
        "offset": 63.2,
        "color": "#869F9A"
      },
      {
        "offset": 68.4,
        "color": "#99A497"
      },
      {
        "offset": 73.7,
        "color": "#ADAA94"
      },
      {
        "offset": 78.9,
        "color": "#C5B39A"
      },
      {
        "offset": 84.2,
        "color": "#DEC3AB"
      },
      {
        "offset": 89.5,
        "color": "#F0D3C1"
      },
      {
        "offset": 94.7,
        "color": "#F9E5DC"
      },
      {
        "offset": 100,
        "color": "#FEF2F2"
      }
    ]
  },
  {
    "name": "lipari",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#021326"
      },
      {
        "offset": 5.3,
        "color": "#06243E"
      },
      {
        "offset": 10.5,
        "color": "#113758"
      },
      {
        "offset": 15.8,
        "color": "#25476C"
      },
      {
        "offset": 21.1,
        "color": "#405579"
      },
      {
        "offset": 26.3,
        "color": "#555B79"
      },
      {
        "offset": 31.6,
        "color": "#665E77"
      },
      {
        "offset": 36.8,
        "color": "#765F72"
      },
      {
        "offset": 42.1,
        "color": "#855F6E"
      },
      {
        "offset": 47.4,
        "color": "#996068"
      },
      {
        "offset": 52.6,
        "color": "#AD6364"
      },
      {
        "offset": 57.9,
        "color": "#C5665F"
      },
      {
        "offset": 63.2,
        "color": "#DA705F"
      },
      {
        "offset": 68.4,
        "color": "#E78065"
      },
      {
        "offset": 73.7,
        "color": "#E99470"
      },
      {
        "offset": 78.9,
        "color": "#E5A57B"
      },
      {
        "offset": 84.2,
        "color": "#E5B88C"
      },
      {
        "offset": 89.5,
        "color": "#E9CAA0"
      },
      {
        "offset": 94.7,
        "color": "#F2DFBE"
      },
      {
        "offset": 100,
        "color": "#FDF4D9"
      }
    ]
  },
  {
    "name": "navia",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#021326"
      },
      {
        "offset": 5.3,
        "color": "#05213F"
      },
      {
        "offset": 10.5,
        "color": "#06325B"
      },
      {
        "offset": 15.8,
        "color": "#0A4373"
      },
      {
        "offset": 21.1,
        "color": "#135387"
      },
      {
        "offset": 26.3,
        "color": "#1D6390"
      },
      {
        "offset": 31.6,
        "color": "#266E90"
      },
      {
        "offset": 36.8,
        "color": "#2C788C"
      },
      {
        "offset": 42.1,
        "color": "#347F87"
      },
      {
        "offset": 47.4,
        "color": "#3D8581"
      },
      {
        "offset": 52.6,
        "color": "#458D7D"
      },
      {
        "offset": 57.9,
        "color": "#509877"
      },
      {
        "offset": 63.2,
        "color": "#5AA171"
      },
      {
        "offset": 68.4,
        "color": "#6AAE6A"
      },
      {
        "offset": 73.7,
        "color": "#80BF67"
      },
      {
        "offset": 78.9,
        "color": "#9FCD72"
      },
      {
        "offset": 84.2,
        "color": "#C0DC8C"
      },
      {
        "offset": 89.5,
        "color": "#D9E5AA"
      },
      {
        "offset": 94.7,
        "color": "#EDEDC5"
      },
      {
        "offset": 100,
        "color": "#FCF3D8"
      }
    ]
  },
  {
    "name": "nuuk",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#05598C"
      },
      {
        "offset": 5.3,
        "color": "#195D87"
      },
      {
        "offset": 10.5,
        "color": "#276184"
      },
      {
        "offset": 15.8,
        "color": "#356781"
      },
      {
        "offset": 21.1,
        "color": "#467083"
      },
      {
        "offset": 26.3,
        "color": "#577985"
      },
      {
        "offset": 31.6,
        "color": "#6A848B"
      },
      {
        "offset": 36.8,
        "color": "#7A8D91"
      },
      {
        "offset": 42.1,
        "color": "#8B9794"
      },
      {
        "offset": 47.4,
        "color": "#99A098"
      },
      {
        "offset": 52.6,
        "color": "#A5A997"
      },
      {
        "offset": 57.9,
        "color": "#AEB093"
      },
      {
        "offset": 63.2,
        "color": "#B6B690"
      },
      {
        "offset": 68.4,
        "color": "#BABA8B"
      },
      {
        "offset": 73.7,
        "color": "#C0C085"
      },
      {
        "offset": 78.9,
        "color": "#C7C783"
      },
      {
        "offset": 84.2,
        "color": "#D2D285"
      },
      {
        "offset": 89.5,
        "color": "#E0E08E"
      },
      {
        "offset": 94.7,
        "color": "#F1F19F"
      },
      {
        "offset": 100,
        "color": "#FEFEB2"
      }
    ]
  },
  {
    "name": "oslo",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#000000"
      },
      {
        "offset": 5.3,
        "color": "#070E17"
      },
      {
        "offset": 10.5,
        "color": "#0C1927"
      },
      {
        "offset": 15.8,
        "color": "#0E2439"
      },
      {
        "offset": 21.1,
        "color": "#12304C"
      },
      {
        "offset": 26.3,
        "color": "#173A5F"
      },
      {
        "offset": 31.6,
        "color": "#1D4774"
      },
      {
        "offset": 36.8,
        "color": "#255488"
      },
      {
        "offset": 42.1,
        "color": "#31619E"
      },
      {
        "offset": 47.4,
        "color": "#4472B2"
      },
      {
        "offset": 52.6,
        "color": "#5981C1"
      },
      {
        "offset": 57.9,
        "color": "#6D90C7"
      },
      {
        "offset": 63.2,
        "color": "#7E99CA"
      },
      {
        "offset": 68.4,
        "color": "#8CA3C9"
      },
      {
        "offset": 73.7,
        "color": "#9EADC9"
      },
      {
        "offset": 78.9,
        "color": "#ADB8CB"
      },
      {
        "offset": 84.2,
        "color": "#C1C6D1"
      },
      {
        "offset": 89.5,
        "color": "#D4D8DC"
      },
      {
        "offset": 94.7,
        "color": "#EBEBEC"
      },
      {
        "offset": 100,
        "color": "#FFFFFF"
      }
    ]
  },
  {
    "name": "tokyo",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#1B0D33"
      },
      {
        "offset": 5.3,
        "color": "#32143A"
      },
      {
        "offset": 10.5,
        "color": "#481F43"
      },
      {
        "offset": 15.8,
        "color": "#5A2C48"
      },
      {
        "offset": 21.1,
        "color": "#663D4D"
      },
      {
        "offset": 26.3,
        "color": "#6C4A50"
      },
      {
        "offset": 31.6,
        "color": "#6E5351"
      },
      {
        "offset": 36.8,
        "color": "#715B52"
      },
      {
        "offset": 42.1,
        "color": "#726352"
      },
      {
        "offset": 47.4,
        "color": "#726B52"
      },
      {
        "offset": 52.6,
        "color": "#737353"
      },
      {
        "offset": 57.9,
        "color": "#777F54"
      },
      {
        "offset": 63.2,
        "color": "#798D57"
      },
      {
        "offset": 68.4,
        "color": "#7D9E59"
      },
      {
        "offset": 73.7,
        "color": "#84B263"
      },
      {
        "offset": 78.9,
        "color": "#91C572"
      },
      {
        "offset": 84.2,
        "color": "#A6DD8D"
      },
      {
        "offset": 89.5,
        "color": "#C3EDAC"
      },
      {
        "offset": 94.7,
        "color": "#DDF8CA"
      },
      {
        "offset": 100,
        "color": "#EEFCDD"
      }
    ]
  },
  {
    "name": "turku",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#000000"
      },
      {
        "offset": 5.3,
        "color": "#141413"
      },
      {
        "offset": 10.5,
        "color": "#22221F"
      },
      {
        "offset": 15.8,
        "color": "#30302A"
      },
      {
        "offset": 21.1,
        "color": "#3F3F33"
      },
      {
        "offset": 26.3,
        "color": "#4C4C3A"
      },
      {
        "offset": 31.6,
        "color": "#5A5A41"
      },
      {
        "offset": 36.8,
        "color": "#676747"
      },
      {
        "offset": 42.1,
        "color": "#77744E"
      },
      {
        "offset": 47.4,
        "color": "#888455"
      },
      {
        "offset": 52.6,
        "color": "#9B925F"
      },
      {
        "offset": 57.9,
        "color": "#B29D6A"
      },
      {
        "offset": 63.2,
        "color": "#C4A473"
      },
      {
        "offset": 68.4,
        "color": "#D2A57F"
      },
      {
        "offset": 73.7,
        "color": "#E0A98C"
      },
      {
        "offset": 78.9,
        "color": "#ECAE9B"
      },
      {
        "offset": 84.2,
        "color": "#F7BAB1"
      },
      {
        "offset": 89.5,
        "color": "#FCC7C4"
      },
      {
        "offset": 94.7,
        "color": "#FFD8D6"
      },
      {
        "offset": 100,
        "color": "#FFE5E5"
      }
    ]
  },
  {
    "name": "blues",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#f7fbff"
      },
      {
        "offset": 12.5,
        "color": "#deebf7"
      },
      {
        "offset": 25,
        "color": "#c6dbef"
      },
      {
        "offset": 37.5,
        "color": "#9ecae1"
      },
      {
        "offset": 50,
        "color": "#6baed6"
      },
      {
        "offset": 62.5,
        "color": "#4292c6"
      },
      {
        "offset": 75,
        "color": "#2171b5"
      },
      {
        "offset": 87.5,
        "color": "#08519c"
      },
      {
        "offset": 100,
        "color": "#08306b"
      }
    ]
  },
  {
    "name": "greens",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#f7fcf5"
      },
      {
        "offset": 12.5,
        "color": "#e5f5e0"
      },
      {
        "offset": 25,
        "color": "#c7e9c0"
      },
      {
        "offset": 37.5,
        "color": "#a1d99b"
      },
      {
        "offset": 50,
        "color": "#74c476"
      },
      {
        "offset": 62.5,
        "color": "#41ab5d"
      },
      {
        "offset": 75,
        "color": "#238b45"
      },
      {
        "offset": 87.5,
        "color": "#006d2c"
      },
      {
        "offset": 100,
        "color": "#00441b"
      }
    ]
  },
  {
    "name": "oranges",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#fff5eb"
      },
      {
        "offset": 12.5,
        "color": "#fee6ce"
      },
      {
        "offset": 25,
        "color": "#fdd0a2"
      },
      {
        "offset": 37.5,
        "color": "#fdae6b"
      },
      {
        "offset": 50,
        "color": "#fd8d3c"
      },
      {
        "offset": 62.5,
        "color": "#f16913"
      },
      {
        "offset": 75,
        "color": "#d94801"
      },
      {
        "offset": 87.5,
        "color": "#a63603"
      },
      {
        "offset": 100,
        "color": "#7f2704"
      }
    ]
  },
  {
    "name": "reds",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#fff5f0"
      },
      {
        "offset": 12.5,
        "color": "#fee0d2"
      },
      {
        "offset": 25,
        "color": "#fcbba1"
      },
      {
        "offset": 37.5,
        "color": "#fc9272"
      },
      {
        "offset": 50,
        "color": "#fb6a4a"
      },
      {
        "offset": 62.5,
        "color": "#ef3b2c"
      },
      {
        "offset": 75,
        "color": "#cb181d"
      },
      {
        "offset": 87.5,
        "color": "#a50f15"
      },
      {
        "offset": 100,
        "color": "#67000d"
      }
    ]
  },
  {
    "name": "purples",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#fcfbfd"
      },
      {
        "offset": 12.5,
        "color": "#efedf5"
      },
      {
        "offset": 25,
        "color": "#dadaeb"
      },
      {
        "offset": 37.5,
        "color": "#bcbddc"
      },
      {
        "offset": 50,
        "color": "#9e9ac8"
      },
      {
        "offset": 62.5,
        "color": "#807dba"
      },
      {
        "offset": 75,
        "color": "#6a51a3"
      },
      {
        "offset": 87.5,
        "color": "#54278f"
      },
      {
        "offset": 100,
        "color": "#3f007d"
      }
    ]
  },
  {
    "name": "greys",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#ffffff"
      },
      {
        "offset": 12.5,
        "color": "#f0f0f0"
      },
      {
        "offset": 25,
        "color": "#d9d9d9"
      },
      {
        "offset": 37.5,
        "color": "#bdbdbd"
      },
      {
        "offset": 50,
        "color": "#969696"
      },
      {
        "offset": 62.5,
        "color": "#737373"
      },
      {
        "offset": 75,
        "color": "#525252"
      },
      {
        "offset": 87.5,
        "color": "#252525"
      },
      {
        "offset": 100,
        "color": "#000000"
      }
    ]
  },
  {
    "name": "ylorbr",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#ffffe5"
      },
      {
        "offset": 12.5,
        "color": "#fff7bc"
      },
      {
        "offset": 25,
        "color": "#fee391"
      },
      {
        "offset": 37.5,
        "color": "#fec44f"
      },
      {
        "offset": 50,
        "color": "#fe9929"
      },
      {
        "offset": 62.5,
        "color": "#ec7014"
      },
      {
        "offset": 75,
        "color": "#cc4c02"
      },
      {
        "offset": 87.5,
        "color": "#993404"
      },
      {
        "offset": 100,
        "color": "#662506"
      }
    ]
  },
  {
    "name": "ylorrd",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#ffffcc"
      },
      {
        "offset": 12.5,
        "color": "#ffeda0"
      },
      {
        "offset": 25,
        "color": "#fed976"
      },
      {
        "offset": 37.5,
        "color": "#feb24c"
      },
      {
        "offset": 50,
        "color": "#fd8d3c"
      },
      {
        "offset": 62.5,
        "color": "#fc4e2a"
      },
      {
        "offset": 75,
        "color": "#e31a1c"
      },
      {
        "offset": 87.5,
        "color": "#bd0026"
      },
      {
        "offset": 100,
        "color": "#800026"
      }
    ]
  },
  {
    "name": "ylgn",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#ffffe5"
      },
      {
        "offset": 12.5,
        "color": "#f7fcb9"
      },
      {
        "offset": 25,
        "color": "#d9f0a3"
      },
      {
        "offset": 37.5,
        "color": "#addd8e"
      },
      {
        "offset": 50,
        "color": "#78c679"
      },
      {
        "offset": 62.5,
        "color": "#41ab5d"
      },
      {
        "offset": 75,
        "color": "#238443"
      },
      {
        "offset": 87.5,
        "color": "#006837"
      },
      {
        "offset": 100,
        "color": "#004529"
      }
    ]
  },
  {
    "name": "ylgnbu",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#ffffd9"
      },
      {
        "offset": 12.5,
        "color": "#edf8b1"
      },
      {
        "offset": 25,
        "color": "#c7e9b4"
      },
      {
        "offset": 37.5,
        "color": "#7fcdbb"
      },
      {
        "offset": 50,
        "color": "#41b6c4"
      },
      {
        "offset": 62.5,
        "color": "#1d91c0"
      },
      {
        "offset": 75,
        "color": "#225ea8"
      },
      {
        "offset": 87.5,
        "color": "#253494"
      },
      {
        "offset": 100,
        "color": "#081d58"
      }
    ]
  },
  {
    "name": "gnbu",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#f7fcf0"
      },
      {
        "offset": 12.5,
        "color": "#e0f3db"
      },
      {
        "offset": 25,
        "color": "#ccebc5"
      },
      {
        "offset": 37.5,
        "color": "#a8ddb5"
      },
      {
        "offset": 50,
        "color": "#7bccc4"
      },
      {
        "offset": 62.5,
        "color": "#4eb3d3"
      },
      {
        "offset": 75,
        "color": "#2b8cbe"
      },
      {
        "offset": 87.5,
        "color": "#0868ac"
      },
      {
        "offset": 100,
        "color": "#084081"
      }
    ]
  },
  {
    "name": "bugn",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#f7fcfd"
      },
      {
        "offset": 12.5,
        "color": "#e5f5f9"
      },
      {
        "offset": 25,
        "color": "#ccece6"
      },
      {
        "offset": 37.5,
        "color": "#99d8c9"
      },
      {
        "offset": 50,
        "color": "#66c2a4"
      },
      {
        "offset": 62.5,
        "color": "#41ae76"
      },
      {
        "offset": 75,
        "color": "#238b45"
      },
      {
        "offset": 87.5,
        "color": "#006d2c"
      },
      {
        "offset": 100,
        "color": "#00441b"
      }
    ]
  },
  {
    "name": "bupu",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#f7fcfd"
      },
      {
        "offset": 12.5,
        "color": "#e0ecf4"
      },
      {
        "offset": 25,
        "color": "#bfd3e6"
      },
      {
        "offset": 37.5,
        "color": "#9ebcda"
      },
      {
        "offset": 50,
        "color": "#8c96c6"
      },
      {
        "offset": 62.5,
        "color": "#8c6bb1"
      },
      {
        "offset": 75,
        "color": "#88419d"
      },
      {
        "offset": 87.5,
        "color": "#810f7c"
      },
      {
        "offset": 100,
        "color": "#4d004b"
      }
    ]
  },
  {
    "name": "pubu",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#fff7fb"
      },
      {
        "offset": 12.5,
        "color": "#ece7f2"
      },
      {
        "offset": 25,
        "color": "#d0d1e6"
      },
      {
        "offset": 37.5,
        "color": "#a6bddb"
      },
      {
        "offset": 50,
        "color": "#74a9cf"
      },
      {
        "offset": 62.5,
        "color": "#3690c0"
      },
      {
        "offset": 75,
        "color": "#0570b0"
      },
      {
        "offset": 87.5,
        "color": "#045a8d"
      },
      {
        "offset": 100,
        "color": "#023858"
      }
    ]
  },
  {
    "name": "pubugn",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#fff7fb"
      },
      {
        "offset": 12.5,
        "color": "#ece2f0"
      },
      {
        "offset": 25,
        "color": "#d0d1e6"
      },
      {
        "offset": 37.5,
        "color": "#a6bddb"
      },
      {
        "offset": 50,
        "color": "#67a9cf"
      },
      {
        "offset": 62.5,
        "color": "#3690c0"
      },
      {
        "offset": 75,
        "color": "#02818a"
      },
      {
        "offset": 87.5,
        "color": "#016c59"
      },
      {
        "offset": 100,
        "color": "#014636"
      }
    ]
  },
  {
    "name": "purd",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#f7f4f9"
      },
      {
        "offset": 12.5,
        "color": "#e7e1ef"
      },
      {
        "offset": 25,
        "color": "#d4b9da"
      },
      {
        "offset": 37.5,
        "color": "#c994c7"
      },
      {
        "offset": 50,
        "color": "#df65b0"
      },
      {
        "offset": 62.5,
        "color": "#e7298a"
      },
      {
        "offset": 75,
        "color": "#ce1256"
      },
      {
        "offset": 87.5,
        "color": "#980043"
      },
      {
        "offset": 100,
        "color": "#67001f"
      }
    ]
  },
  {
    "name": "rdpu",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#fff7f3"
      },
      {
        "offset": 12.5,
        "color": "#fde0dd"
      },
      {
        "offset": 25,
        "color": "#fcc5c0"
      },
      {
        "offset": 37.5,
        "color": "#fa9fb5"
      },
      {
        "offset": 50,
        "color": "#f768a1"
      },
      {
        "offset": 62.5,
        "color": "#dd3497"
      },
      {
        "offset": 75,
        "color": "#ae017e"
      },
      {
        "offset": 87.5,
        "color": "#7a0177"
      },
      {
        "offset": 100,
        "color": "#49006a"
      }
    ]
  },
  {
    "name": "orrd",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#fff7ec"
      },
      {
        "offset": 12.5,
        "color": "#fee8c8"
      },
      {
        "offset": 25,
        "color": "#fdd49e"
      },
      {
        "offset": 37.5,
        "color": "#fdbb84"
      },
      {
        "offset": 50,
        "color": "#fc8d59"
      },
      {
        "offset": 62.5,
        "color": "#ef6548"
      },
      {
        "offset": 75,
        "color": "#d7301f"
      },
      {
        "offset": 87.5,
        "color": "#b30000"
      },
      {
        "offset": 100,
        "color": "#7f0000"
      }
    ]
  },
  {
    "name": "viridis",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#440154"
      },
      {
        "offset": 5.3,
        "color": "#471466"
      },
      {
        "offset": 10.5,
        "color": "#472676"
      },
      {
        "offset": 15.8,
        "color": "#453681"
      },
      {
        "offset": 21.1,
        "color": "#3f4788"
      },
      {
        "offset": 26.3,
        "color": "#39558b"
      },
      {
        "offset": 31.6,
        "color": "#32638d"
      },
      {
        "offset": 36.8,
        "color": "#2c708e"
      },
      {
        "offset": 42.1,
        "color": "#277c8e"
      },
      {
        "offset": 47.4,
        "color": "#22898d"
      },
      {
        "offset": 52.6,
        "color": "#1f968b"
      },
      {
        "offset": 57.9,
        "color": "#1fa386"
      },
      {
        "offset": 63.2,
        "color": "#29af7f"
      },
      {
        "offset": 68.4,
        "color": "#3bba75"
      },
      {
        "offset": 73.7,
        "color": "#55c666"
      },
      {
        "offset": 78.9,
        "color": "#72cf55"
      },
      {
        "offset": 84.2,
        "color": "#95d73f"
      },
      {
        "offset": 89.5,
        "color": "#b7dd29"
      },
      {
        "offset": 94.7,
        "color": "#dce218"
      },
      {
        "offset": 100,
        "color": "#fde724"
      }
    ]
  },
  {
    "name": "plasma",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#0c0786"
      },
      {
        "offset": 5.3,
        "color": "#2b0594"
      },
      {
        "offset": 10.5,
        "color": "#44039e"
      },
      {
        "offset": 15.8,
        "color": "#5901a4"
      },
      {
        "offset": 21.1,
        "color": "#6f00a8"
      },
      {
        "offset": 26.3,
        "color": "#8204a7"
      },
      {
        "offset": 31.6,
        "color": "#9612a0"
      },
      {
        "offset": 36.8,
        "color": "#a72197"
      },
      {
        "offset": 42.1,
        "color": "#b62f8b"
      },
      {
        "offset": 47.4,
        "color": "#c43f7e"
      },
      {
        "offset": 52.6,
        "color": "#d14e72"
      },
      {
        "offset": 57.9,
        "color": "#dc5e66"
      },
      {
        "offset": 63.2,
        "color": "#e66d5a"
      },
      {
        "offset": 68.4,
        "color": "#ef7d4f"
      },
      {
        "offset": 73.7,
        "color": "#f68f43"
      },
      {
        "offset": 78.9,
        "color": "#fba238"
      },
      {
        "offset": 84.2,
        "color": "#fdb62d"
      },
      {
        "offset": 89.5,
        "color": "#fccb25"
      },
      {
        "offset": 94.7,
        "color": "#f7e225"
      },
      {
        "offset": 100,
        "color": "#eff821"
      }
    ]
  },
  {
    "name": "magma",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#000003"
      },
      {
        "offset": 5.3,
        "color": "#07051b"
      },
      {
        "offset": 10.5,
        "color": "#160e3a"
      },
      {
        "offset": 15.8,
        "color": "#281159"
      },
      {
        "offset": 21.1,
        "color": "#400f73"
      },
      {
        "offset": 26.3,
        "color": "#55137d"
      },
      {
        "offset": 31.6,
        "color": "#6b1c80"
      },
      {
        "offset": 36.8,
        "color": "#7f2481"
      },
      {
        "offset": 42.1,
        "color": "#942b80"
      },
      {
        "offset": 47.4,
        "color": "#ab337c"
      },
      {
        "offset": 52.6,
        "color": "#c03a75"
      },
      {
        "offset": 57.9,
        "color": "#d6446c"
      },
      {
        "offset": 63.2,
        "color": "#e75262"
      },
      {
        "offset": 68.4,
        "color": "#f3675b"
      },
      {
        "offset": 73.7,
        "color": "#fa805e"
      },
      {
        "offset": 78.9,
        "color": "#fd9969"
      },
      {
        "offset": 84.2,
        "color": "#feb37b"
      },
      {
        "offset": 89.5,
        "color": "#fecb8e"
      },
      {
        "offset": 94.7,
        "color": "#fce5a6"
      },
      {
        "offset": 100,
        "color": "#fbfcbf"
      }
    ]
  },
  {
    "name": "inferno",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#000003"
      },
      {
        "offset": 5.3,
        "color": "#07051d"
      },
      {
        "offset": 10.5,
        "color": "#190b3e"
      },
      {
        "offset": 15.8,
        "color": "#2e0a5a"
      },
      {
        "offset": 21.1,
        "color": "#460a69"
      },
      {
        "offset": 26.3,
        "color": "#5b116e"
      },
      {
        "offset": 31.6,
        "color": "#72196d"
      },
      {
        "offset": 36.8,
        "color": "#86216a"
      },
      {
        "offset": 42.1,
        "color": "#9b2864"
      },
      {
        "offset": 47.4,
        "color": "#b1315a"
      },
      {
        "offset": 52.6,
        "color": "#c43c4e"
      },
      {
        "offset": 57.9,
        "color": "#d64a3f"
      },
      {
        "offset": 63.2,
        "color": "#e55b30"
      },
      {
        "offset": 68.4,
        "color": "#f06f1f"
      },
      {
        "offset": 73.7,
        "color": "#f8870d"
      },
      {
        "offset": 78.9,
        "color": "#fb9e07"
      },
      {
        "offset": 84.2,
        "color": "#fbb91e"
      },
      {
        "offset": 89.5,
        "color": "#f6d33f"
      },
      {
        "offset": 94.7,
        "color": "#f1ed70"
      },
      {
        "offset": 100,
        "color": "#fcfea4"
      }
    ]
  },
  {
    "name": "cividis",
    "category": "sequential",
    "stops": [
      {
        "offset": 0,
        "color": "#00224d"
      },
      {
        "offset": 5.3,
        "color": "#002b64"
      },
      {
        "offset": 10.5,
        "color": "#0e3470"
      },
      {
        "offset": 15.8,
        "color": "#273d6d"
      },
      {
        "offset": 21.1,
        "color": "#38476c"
      },
      {
        "offset": 26.3,
        "color": "#46506b"
      },
      {
        "offset": 31.6,
        "color": "#535a6c"
      },
      {
        "offset": 36.8,
        "color": "#5f636e"
      },
      {
        "offset": 42.1,
        "color": "#6a6c71"
      },
      {
        "offset": 47.4,
        "color": "#767676"
      },
      {
        "offset": 52.6,
        "color": "#828078"
      },
      {
        "offset": 57.9,
        "color": "#8f8a77"
      },
      {
        "offset": 63.2,
        "color": "#9c9476"
      },
      {
        "offset": 68.4,
        "color": "#a99e72"
      },
      {
        "offset": 73.7,
        "color": "#b7aa6d"
      },
      {
        "offset": 78.9,
        "color": "#c5b567"
      },
      {
        "offset": 84.2,
        "color": "#d4c15e"
      },
      {
        "offset": 89.5,
        "color": "#e2cc53"
      },
      {
        "offset": 94.7,
        "color": "#f2da43"
      },
      {
        "offset": 100,
        "color": "#fde737"
      }
    ]
  },
  {
    "name": "vik",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#001260"
      },
      {
        "offset": 5.3,
        "color": "#01266D"
      },
      {
        "offset": 10.5,
        "color": "#023B7B"
      },
      {
        "offset": 15.8,
        "color": "#055188"
      },
      {
        "offset": 21.1,
        "color": "#176899"
      },
      {
        "offset": 26.3,
        "color": "#3983AB"
      },
      {
        "offset": 31.6,
        "color": "#649FBE"
      },
      {
        "offset": 36.8,
        "color": "#8CB9D0"
      },
      {
        "offset": 42.1,
        "color": "#B6D2E0"
      },
      {
        "offset": 47.4,
        "color": "#DFE5E9"
      },
      {
        "offset": 52.6,
        "color": "#EDDDD2"
      },
      {
        "offset": 57.9,
        "color": "#E5C0AC"
      },
      {
        "offset": 63.2,
        "color": "#DAA78B"
      },
      {
        "offset": 68.4,
        "color": "#D0906B"
      },
      {
        "offset": 73.7,
        "color": "#C5774A"
      },
      {
        "offset": 78.9,
        "color": "#BA5F2C"
      },
      {
        "offset": 84.2,
        "color": "#A53F0E"
      },
      {
        "offset": 89.5,
        "color": "#882606"
      },
      {
        "offset": 94.7,
        "color": "#6E1106"
      },
      {
        "offset": 100,
        "color": "#590007"
      }
    ]
  },
  {
    "name": "berlin",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#9EB0FF"
      },
      {
        "offset": 5.3,
        "color": "#7FACF1"
      },
      {
        "offset": 10.5,
        "color": "#5DA5DD"
      },
      {
        "offset": 15.8,
        "color": "#4093C0"
      },
      {
        "offset": 21.1,
        "color": "#30799E"
      },
      {
        "offset": 26.3,
        "color": "#26617F"
      },
      {
        "offset": 31.6,
        "color": "#1B485F"
      },
      {
        "offset": 36.8,
        "color": "#143341"
      },
      {
        "offset": 42.1,
        "color": "#111F27"
      },
      {
        "offset": 47.4,
        "color": "#131112"
      },
      {
        "offset": 52.6,
        "color": "#1F0B04"
      },
      {
        "offset": 57.9,
        "color": "#300E00"
      },
      {
        "offset": 63.2,
        "color": "#411300"
      },
      {
        "offset": 68.4,
        "color": "#571A06"
      },
      {
        "offset": 73.7,
        "color": "#742C17"
      },
      {
        "offset": 78.9,
        "color": "#904430"
      },
      {
        "offset": 84.2,
        "color": "#AC5E4E"
      },
      {
        "offset": 89.5,
        "color": "#C5776C"
      },
      {
        "offset": 94.7,
        "color": "#E3928D"
      },
      {
        "offset": 100,
        "color": "#FFACAC"
      }
    ]
  },
  {
    "name": "roma",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#7E1700"
      },
      {
        "offset": 5.3,
        "color": "#8C350A"
      },
      {
        "offset": 10.5,
        "color": "#995013"
      },
      {
        "offset": 15.8,
        "color": "#A3651E"
      },
      {
        "offset": 21.1,
        "color": "#AD7B27"
      },
      {
        "offset": 26.3,
        "color": "#B89234"
      },
      {
        "offset": 31.6,
        "color": "#C5AC4C"
      },
      {
        "offset": 36.8,
        "color": "#CEC56C"
      },
      {
        "offset": 42.1,
        "color": "#D2DC92"
      },
      {
        "offset": 47.4,
        "color": "#C9E9B6"
      },
      {
        "offset": 52.6,
        "color": "#B4EACC"
      },
      {
        "offset": 57.9,
        "color": "#94DFD6"
      },
      {
        "offset": 63.2,
        "color": "#73CED6"
      },
      {
        "offset": 68.4,
        "color": "#54B9D1"
      },
      {
        "offset": 73.7,
        "color": "#3DA1C9"
      },
      {
        "offset": 78.9,
        "color": "#308CBF"
      },
      {
        "offset": 84.2,
        "color": "#2677B7"
      },
      {
        "offset": 89.5,
        "color": "#1F61AD"
      },
      {
        "offset": 94.7,
        "color": "#154AA3"
      },
      {
        "offset": 100,
        "color": "#023198"
      }
    ]
  },
  {
    "name": "bam",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#65014B"
      },
      {
        "offset": 5.3,
        "color": "#802067"
      },
      {
        "offset": 10.5,
        "color": "#9D3983"
      },
      {
        "offset": 15.8,
        "color": "#B25099"
      },
      {
        "offset": 21.1,
        "color": "#C56AAD"
      },
      {
        "offset": 26.3,
        "color": "#D385BF"
      },
      {
        "offset": 31.6,
        "color": "#E0A5D1"
      },
      {
        "offset": 36.8,
        "color": "#EBC1DF"
      },
      {
        "offset": 42.1,
        "color": "#F2D9EB"
      },
      {
        "offset": 47.4,
        "color": "#F6EBF1"
      },
      {
        "offset": 52.6,
        "color": "#F3F2EC"
      },
      {
        "offset": 57.9,
        "color": "#E7F0DA"
      },
      {
        "offset": 63.2,
        "color": "#D3E5BD"
      },
      {
        "offset": 68.4,
        "color": "#B7D294"
      },
      {
        "offset": 73.7,
        "color": "#93BA6C"
      },
      {
        "offset": 78.9,
        "color": "#76A350"
      },
      {
        "offset": 84.2,
        "color": "#598C39"
      },
      {
        "offset": 89.5,
        "color": "#447928"
      },
      {
        "offset": 94.7,
        "color": "#2A6314"
      },
      {
        "offset": 100,
        "color": "#0C4C00"
      }
    ]
  },
  {
    "name": "broc",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#2C194C"
      },
      {
        "offset": 5.3,
        "color": "#2A2C5F"
      },
      {
        "offset": 10.5,
        "color": "#274374"
      },
      {
        "offset": 15.8,
        "color": "#2D5888"
      },
      {
        "offset": 21.1,
        "color": "#45719B"
      },
      {
        "offset": 26.3,
        "color": "#6086AC"
      },
      {
        "offset": 31.6,
        "color": "#819FBD"
      },
      {
        "offset": 36.8,
        "color": "#9FB7CC"
      },
      {
        "offset": 42.1,
        "color": "#BFCEDD"
      },
      {
        "offset": 47.4,
        "color": "#DFE6EB"
      },
      {
        "offset": 52.6,
        "color": "#EDEEE3"
      },
      {
        "offset": 57.9,
        "color": "#E0E0C4"
      },
      {
        "offset": 63.2,
        "color": "#D2D2A5"
      },
      {
        "offset": 68.4,
        "color": "#BEBE85"
      },
      {
        "offset": 73.7,
        "color": "#A0A066"
      },
      {
        "offset": 78.9,
        "color": "#868651"
      },
      {
        "offset": 84.2,
        "color": "#6C6C39"
      },
      {
        "offset": 89.5,
        "color": "#535326"
      },
      {
        "offset": 94.7,
        "color": "#3A3A12"
      },
      {
        "offset": 100,
        "color": "#262600"
      }
    ]
  },
  {
    "name": "cork",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#2C194C"
      },
      {
        "offset": 5.3,
        "color": "#2A2D60"
      },
      {
        "offset": 10.5,
        "color": "#274376"
      },
      {
        "offset": 15.8,
        "color": "#2C598A"
      },
      {
        "offset": 21.1,
        "color": "#43709B"
      },
      {
        "offset": 26.3,
        "color": "#5B83A9"
      },
      {
        "offset": 31.6,
        "color": "#7999B8"
      },
      {
        "offset": 36.8,
        "color": "#99B1C9"
      },
      {
        "offset": 42.1,
        "color": "#B9CBDA"
      },
      {
        "offset": 47.4,
        "color": "#DEE5EB"
      },
      {
        "offset": 52.6,
        "color": "#E1EBE3"
      },
      {
        "offset": 57.9,
        "color": "#C4D7C3"
      },
      {
        "offset": 63.2,
        "color": "#A4C1A3"
      },
      {
        "offset": 68.4,
        "color": "#84AC84"
      },
      {
        "offset": 73.7,
        "color": "#649764"
      },
      {
        "offset": 78.9,
        "color": "#488547"
      },
      {
        "offset": 84.2,
        "color": "#2C702C"
      },
      {
        "offset": 89.5,
        "color": "#1A5917"
      },
      {
        "offset": 94.7,
        "color": "#133F0C"
      },
      {
        "offset": 100,
        "color": "#0E2802"
      }
    ]
  },
  {
    "name": "lisbon",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#E5E5FF"
      },
      {
        "offset": 5.3,
        "color": "#C3CCEA"
      },
      {
        "offset": 10.5,
        "color": "#9EB1D3"
      },
      {
        "offset": 15.8,
        "color": "#7B98BF"
      },
      {
        "offset": 21.1,
        "color": "#597DA9"
      },
      {
        "offset": 26.3,
        "color": "#396491"
      },
      {
        "offset": 31.6,
        "color": "#214A71"
      },
      {
        "offset": 36.8,
        "color": "#173552"
      },
      {
        "offset": 42.1,
        "color": "#122437"
      },
      {
        "offset": 47.4,
        "color": "#13191F"
      },
      {
        "offset": 52.6,
        "color": "#1B1B17"
      },
      {
        "offset": 57.9,
        "color": "#302C1E"
      },
      {
        "offset": 63.2,
        "color": "#46412A"
      },
      {
        "offset": 68.4,
        "color": "#5E5838"
      },
      {
        "offset": 73.7,
        "color": "#797248"
      },
      {
        "offset": 78.9,
        "color": "#938B5A"
      },
      {
        "offset": 84.2,
        "color": "#B1A974"
      },
      {
        "offset": 89.5,
        "color": "#CBC592"
      },
      {
        "offset": 94.7,
        "color": "#E5E3B6"
      },
      {
        "offset": 100,
        "color": "#FFFFD8"
      }
    ]
  },
  {
    "name": "managua",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#FFCE66"
      },
      {
        "offset": 5.3,
        "color": "#EEB45E"
      },
      {
        "offset": 10.5,
        "color": "#DE9B55"
      },
      {
        "offset": 15.8,
        "color": "#CD854E"
      },
      {
        "offset": 21.1,
        "color": "#BD7046"
      },
      {
        "offset": 26.3,
        "color": "#AC5E41"
      },
      {
        "offset": 31.6,
        "color": "#984B3B"
      },
      {
        "offset": 36.8,
        "color": "#843A39"
      },
      {
        "offset": 42.1,
        "color": "#702E39"
      },
      {
        "offset": 47.4,
        "color": "#5E2841"
      },
      {
        "offset": 52.6,
        "color": "#522B51"
      },
      {
        "offset": 57.9,
        "color": "#4C376A"
      },
      {
        "offset": 63.2,
        "color": "#4C4783"
      },
      {
        "offset": 68.4,
        "color": "#4E5A99"
      },
      {
        "offset": 73.7,
        "color": "#5571AE"
      },
      {
        "offset": 78.9,
        "color": "#5D85BF"
      },
      {
        "offset": 84.2,
        "color": "#669BD0"
      },
      {
        "offset": 89.5,
        "color": "#6DB2DF"
      },
      {
        "offset": 94.7,
        "color": "#78CCF0"
      },
      {
        "offset": 100,
        "color": "#80E6FF"
      }
    ]
  },
  {
    "name": "tofino",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#DED8FF"
      },
      {
        "offset": 5.3,
        "color": "#BABFF0"
      },
      {
        "offset": 10.5,
        "color": "#96A5DF"
      },
      {
        "offset": 15.8,
        "color": "#728CCD"
      },
      {
        "offset": 21.1,
        "color": "#5171B3"
      },
      {
        "offset": 26.3,
        "color": "#395992"
      },
      {
        "offset": 31.6,
        "color": "#2B416E"
      },
      {
        "offset": 36.8,
        "color": "#1F304E"
      },
      {
        "offset": 42.1,
        "color": "#141F32"
      },
      {
        "offset": 47.4,
        "color": "#0D1419"
      },
      {
        "offset": 52.6,
        "color": "#0D1911"
      },
      {
        "offset": 57.9,
        "color": "#142A17"
      },
      {
        "offset": 63.2,
        "color": "#1D3E1F"
      },
      {
        "offset": 68.4,
        "color": "#26532C"
      },
      {
        "offset": 73.7,
        "color": "#336C39"
      },
      {
        "offset": 78.9,
        "color": "#448646"
      },
      {
        "offset": 84.2,
        "color": "#64A45B"
      },
      {
        "offset": 89.5,
        "color": "#8BBA71"
      },
      {
        "offset": 94.7,
        "color": "#B4D186"
      },
      {
        "offset": 100,
        "color": "#DAE59A"
      }
    ]
  },
  {
    "name": "vanimo",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#FFCCFD"
      },
      {
        "offset": 5.3,
        "color": "#EBA7E1"
      },
      {
        "offset": 10.5,
        "color": "#D484C5"
      },
      {
        "offset": 15.8,
        "color": "#BF66AD"
      },
      {
        "offset": 21.1,
        "color": "#A64D93"
      },
      {
        "offset": 26.3,
        "color": "#8B3979"
      },
      {
        "offset": 31.6,
        "color": "#662859"
      },
      {
        "offset": 36.8,
        "color": "#451B3A"
      },
      {
        "offset": 42.1,
        "color": "#2A1424"
      },
      {
        "offset": 47.4,
        "color": "#1B1315"
      },
      {
        "offset": 52.6,
        "color": "#191811"
      },
      {
        "offset": 57.9,
        "color": "#1F2512"
      },
      {
        "offset": 63.2,
        "color": "#2B3915"
      },
      {
        "offset": 68.4,
        "color": "#3A511B"
      },
      {
        "offset": 73.7,
        "color": "#4C6B24"
      },
      {
        "offset": 78.9,
        "color": "#5E802C"
      },
      {
        "offset": 84.2,
        "color": "#719A39"
      },
      {
        "offset": 89.5,
        "color": "#86B74E"
      },
      {
        "offset": 94.7,
        "color": "#A1D974"
      },
      {
        "offset": 100,
        "color": "#BEFDA5"
      }
    ]
  },
  {
    "name": "rdbu",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#67001f"
      },
      {
        "offset": 10,
        "color": "#b2182b"
      },
      {
        "offset": 20,
        "color": "#d6604d"
      },
      {
        "offset": 30,
        "color": "#f4a582"
      },
      {
        "offset": 40,
        "color": "#fddbc7"
      },
      {
        "offset": 50,
        "color": "#f7f7f7"
      },
      {
        "offset": 60,
        "color": "#d1e5f0"
      },
      {
        "offset": 70,
        "color": "#92c5de"
      },
      {
        "offset": 80,
        "color": "#4393c3"
      },
      {
        "offset": 90,
        "color": "#2166ac"
      },
      {
        "offset": 100,
        "color": "#053061"
      }
    ]
  },
  {
    "name": "rdylbu",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#a50026"
      },
      {
        "offset": 10,
        "color": "#d73027"
      },
      {
        "offset": 20,
        "color": "#f46d43"
      },
      {
        "offset": 30,
        "color": "#fdae61"
      },
      {
        "offset": 40,
        "color": "#fee090"
      },
      {
        "offset": 50,
        "color": "#ffffbf"
      },
      {
        "offset": 60,
        "color": "#e0f3f8"
      },
      {
        "offset": 70,
        "color": "#abd9e9"
      },
      {
        "offset": 80,
        "color": "#74add1"
      },
      {
        "offset": 90,
        "color": "#4575b4"
      },
      {
        "offset": 100,
        "color": "#313695"
      }
    ]
  },
  {
    "name": "rdylgn",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#a50026"
      },
      {
        "offset": 10,
        "color": "#d73027"
      },
      {
        "offset": 20,
        "color": "#f46d43"
      },
      {
        "offset": 30,
        "color": "#fdae61"
      },
      {
        "offset": 40,
        "color": "#fee08b"
      },
      {
        "offset": 50,
        "color": "#ffffbf"
      },
      {
        "offset": 60,
        "color": "#d9ef8b"
      },
      {
        "offset": 70,
        "color": "#a6d96a"
      },
      {
        "offset": 80,
        "color": "#66bd63"
      },
      {
        "offset": 90,
        "color": "#1a9850"
      },
      {
        "offset": 100,
        "color": "#006837"
      }
    ]
  },
  {
    "name": "spectral",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#9e0142"
      },
      {
        "offset": 10,
        "color": "#d53e4f"
      },
      {
        "offset": 20,
        "color": "#f46d43"
      },
      {
        "offset": 30,
        "color": "#fdae61"
      },
      {
        "offset": 40,
        "color": "#fee08b"
      },
      {
        "offset": 50,
        "color": "#ffffbf"
      },
      {
        "offset": 60,
        "color": "#e6f598"
      },
      {
        "offset": 70,
        "color": "#abdda4"
      },
      {
        "offset": 80,
        "color": "#66c2a5"
      },
      {
        "offset": 90,
        "color": "#3288bd"
      },
      {
        "offset": 100,
        "color": "#5e4fa2"
      }
    ]
  },
  {
    "name": "brbg",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#543005"
      },
      {
        "offset": 10,
        "color": "#8c510a"
      },
      {
        "offset": 20,
        "color": "#bf812d"
      },
      {
        "offset": 30,
        "color": "#dfc27d"
      },
      {
        "offset": 40,
        "color": "#f6e8c3"
      },
      {
        "offset": 50,
        "color": "#f5f5f5"
      },
      {
        "offset": 60,
        "color": "#c7eae5"
      },
      {
        "offset": 70,
        "color": "#80cdc1"
      },
      {
        "offset": 80,
        "color": "#35978f"
      },
      {
        "offset": 90,
        "color": "#01665e"
      },
      {
        "offset": 100,
        "color": "#003c30"
      }
    ]
  },
  {
    "name": "prgn",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#40004b"
      },
      {
        "offset": 10,
        "color": "#762a83"
      },
      {
        "offset": 20,
        "color": "#9970ab"
      },
      {
        "offset": 30,
        "color": "#c2a5cf"
      },
      {
        "offset": 40,
        "color": "#e7d4e8"
      },
      {
        "offset": 50,
        "color": "#f7f7f7"
      },
      {
        "offset": 60,
        "color": "#d9f0d3"
      },
      {
        "offset": 70,
        "color": "#a6dba0"
      },
      {
        "offset": 80,
        "color": "#5aae61"
      },
      {
        "offset": 90,
        "color": "#1b7837"
      },
      {
        "offset": 100,
        "color": "#00441b"
      }
    ]
  },
  {
    "name": "piyg",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#8e0152"
      },
      {
        "offset": 10,
        "color": "#c51b7d"
      },
      {
        "offset": 20,
        "color": "#de77ae"
      },
      {
        "offset": 30,
        "color": "#f1b6da"
      },
      {
        "offset": 40,
        "color": "#fde0ef"
      },
      {
        "offset": 50,
        "color": "#f7f7f7"
      },
      {
        "offset": 60,
        "color": "#e6f5d0"
      },
      {
        "offset": 70,
        "color": "#b8e186"
      },
      {
        "offset": 80,
        "color": "#7fbc41"
      },
      {
        "offset": 90,
        "color": "#4d9221"
      },
      {
        "offset": 100,
        "color": "#276419"
      }
    ]
  },
  {
    "name": "rdgy",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#67001f"
      },
      {
        "offset": 10,
        "color": "#b2182b"
      },
      {
        "offset": 20,
        "color": "#d6604d"
      },
      {
        "offset": 30,
        "color": "#f4a582"
      },
      {
        "offset": 40,
        "color": "#fddbc7"
      },
      {
        "offset": 50,
        "color": "#ffffff"
      },
      {
        "offset": 60,
        "color": "#e0e0e0"
      },
      {
        "offset": 70,
        "color": "#bababa"
      },
      {
        "offset": 80,
        "color": "#878787"
      },
      {
        "offset": 90,
        "color": "#4d4d4d"
      },
      {
        "offset": 100,
        "color": "#1a1a1a"
      }
    ]
  },
  {
    "name": "puor",
    "category": "diverging",
    "stops": [
      {
        "offset": 0,
        "color": "#7f3b08"
      },
      {
        "offset": 10,
        "color": "#b35806"
      },
      {
        "offset": 20,
        "color": "#e08214"
      },
      {
        "offset": 30,
        "color": "#fdb863"
      },
      {
        "offset": 40,
        "color": "#fee0b6"
      },
      {
        "offset": 50,
        "color": "#f7f7f7"
      },
      {
        "offset": 60,
        "color": "#d8daeb"
      },
      {
        "offset": 70,
        "color": "#b2abd2"
      },
      {
        "offset": 80,
        "color": "#8073ac"
      },
      {
        "offset": 90,
        "color": "#542788"
      },
      {
        "offset": 100,
        "color": "#2d004b"
      }
    ]
  },
  {
    "name": "bukavu",
    "category": "multi",
    "stops": [
      {
        "offset": 0,
        "color": "#193333"
      },
      {
        "offset": 5.3,
        "color": "#1D3E4D"
      },
      {
        "offset": 10.5,
        "color": "#204E74"
      },
      {
        "offset": 15.8,
        "color": "#27669B"
      },
      {
        "offset": 21.1,
        "color": "#317FBD"
      },
      {
        "offset": 26.3,
        "color": "#4597C7"
      },
      {
        "offset": 31.6,
        "color": "#5FADCA"
      },
      {
        "offset": 36.8,
        "color": "#76C3CB"
      },
      {
        "offset": 42.1,
        "color": "#9DD9D2"
      },
      {
        "offset": 47.4,
        "color": "#CEF3DF"
      },
      {
        "offset": 52.6,
        "color": "#06461F"
      },
      {
        "offset": 57.9,
        "color": "#215D13"
      },
      {
        "offset": 63.2,
        "color": "#4D6D1A"
      },
      {
        "offset": 68.4,
        "color": "#73742C"
      },
      {
        "offset": 73.7,
        "color": "#927A3E"
      },
      {
        "offset": 78.9,
        "color": "#B08857"
      },
      {
        "offset": 84.2,
        "color": "#C5A681"
      },
      {
        "offset": 89.5,
        "color": "#D3C4AC"
      },
      {
        "offset": 94.7,
        "color": "#E1DAD8"
      },
      {
        "offset": 100,
        "color": "#ECECFC"
      }
    ]
  },
  {
    "name": "fes",
    "category": "multi",
    "stops": [
      {
        "offset": 0,
        "color": "#0C0C0C"
      },
      {
        "offset": 5.3,
        "color": "#262626"
      },
      {
        "offset": 10.5,
        "color": "#3E3E3E"
      },
      {
        "offset": 15.8,
        "color": "#525252"
      },
      {
        "offset": 21.1,
        "color": "#676767"
      },
      {
        "offset": 26.3,
        "color": "#7A7A7A"
      },
      {
        "offset": 31.6,
        "color": "#909090"
      },
      {
        "offset": 36.8,
        "color": "#A6A6A6"
      },
      {
        "offset": 42.1,
        "color": "#C0C0C0"
      },
      {
        "offset": 47.4,
        "color": "#E1E1E1"
      },
      {
        "offset": 52.6,
        "color": "#144621"
      },
      {
        "offset": 57.9,
        "color": "#3F5420"
      },
      {
        "offset": 63.2,
        "color": "#605E26"
      },
      {
        "offset": 68.4,
        "color": "#7F662C"
      },
      {
        "offset": 73.7,
        "color": "#A07137"
      },
      {
        "offset": 78.9,
        "color": "#B98855"
      },
      {
        "offset": 84.2,
        "color": "#C7A781"
      },
      {
        "offset": 89.5,
        "color": "#D3C4AC"
      },
      {
        "offset": 94.7,
        "color": "#E1DAD8"
      },
      {
        "offset": 100,
        "color": "#ECECFC"
      }
    ]
  },
  {
    "name": "oleron",
    "category": "multi",
    "stops": [
      {
        "offset": 0,
        "color": "#192659"
      },
      {
        "offset": 5.3,
        "color": "#2D396C"
      },
      {
        "offset": 10.5,
        "color": "#445083"
      },
      {
        "offset": 15.8,
        "color": "#596699"
      },
      {
        "offset": 21.1,
        "color": "#727EB1"
      },
      {
        "offset": 26.3,
        "color": "#8896C9"
      },
      {
        "offset": 31.6,
        "color": "#A3AEE0"
      },
      {
        "offset": 36.8,
        "color": "#B8C5F2"
      },
      {
        "offset": 42.1,
        "color": "#CBD8F8"
      },
      {
        "offset": 47.4,
        "color": "#DEEAFD"
      },
      {
        "offset": 52.6,
        "color": "#2A5100"
      },
      {
        "offset": 57.9,
        "color": "#485900"
      },
      {
        "offset": 63.2,
        "color": "#65660C"
      },
      {
        "offset": 68.4,
        "color": "#837627"
      },
      {
        "offset": 73.7,
        "color": "#A08A46"
      },
      {
        "offset": 78.9,
        "color": "#BE9F65"
      },
      {
        "offset": 84.2,
        "color": "#DEB885"
      },
      {
        "offset": 89.5,
        "color": "#F2D0A6"
      },
      {
        "offset": 94.7,
        "color": "#F8E6C6"
      },
      {
        "offset": 100,
        "color": "#FDFDE5"
      }
    ]
  },
  {
    "name": "romao",
    "category": "cyclic",
    "stops": [
      {
        "offset": 0,
        "color": "#723957"
      },
      {
        "offset": 5.3,
        "color": "#7B3946"
      },
      {
        "offset": 10.5,
        "color": "#863F37"
      },
      {
        "offset": 15.8,
        "color": "#924C2E"
      },
      {
        "offset": 21.1,
        "color": "#9F612B"
      },
      {
        "offset": 26.3,
        "color": "#AD7A31"
      },
      {
        "offset": 31.6,
        "color": "#BE9944"
      },
      {
        "offset": 36.8,
        "color": "#CCB860"
      },
      {
        "offset": 42.1,
        "color": "#D4D083"
      },
      {
        "offset": 47.4,
        "color": "#D2DFA5"
      },
      {
        "offset": 52.6,
        "color": "#C1E0BB"
      },
      {
        "offset": 57.9,
        "color": "#A6D8CB"
      },
      {
        "offset": 63.2,
        "color": "#87C9CE"
      },
      {
        "offset": 68.4,
        "color": "#6CB3CC"
      },
      {
        "offset": 73.7,
        "color": "#579AC3"
      },
      {
        "offset": 78.9,
        "color": "#4E81B6"
      },
      {
        "offset": 84.2,
        "color": "#5266A0"
      },
      {
        "offset": 89.5,
        "color": "#5B5288"
      },
      {
        "offset": 94.7,
        "color": "#67406D"
      },
      {
        "offset": 100,
        "color": "#723959"
      }
    ]
  },
  {
    "name": "bamo",
    "category": "cyclic",
    "stops": [
      {
        "offset": 0,
        "color": "#4E3043"
      },
      {
        "offset": 5.3,
        "color": "#66355A"
      },
      {
        "offset": 10.5,
        "color": "#854777"
      },
      {
        "offset": 15.8,
        "color": "#9D5A8C"
      },
      {
        "offset": 21.1,
        "color": "#B272A3"
      },
      {
        "offset": 26.3,
        "color": "#C58BB6"
      },
      {
        "offset": 31.6,
        "color": "#D4A9C6"
      },
      {
        "offset": 36.8,
        "color": "#D9BECC"
      },
      {
        "offset": 42.1,
        "color": "#D8C9C9"
      },
      {
        "offset": 47.4,
        "color": "#D2CCC1"
      },
      {
        "offset": 52.6,
        "color": "#C7CBB2"
      },
      {
        "offset": 57.9,
        "color": "#ACB991"
      },
      {
        "offset": 63.2,
        "color": "#92A073"
      },
      {
        "offset": 68.4,
        "color": "#7D8A5F"
      },
      {
        "offset": 73.7,
        "color": "#6C7351"
      },
      {
        "offset": 78.9,
        "color": "#5E5F46"
      },
      {
        "offset": 84.2,
        "color": "#524D3F"
      },
      {
        "offset": 89.5,
        "color": "#4B403A"
      },
      {
        "offset": 94.7,
        "color": "#47353A"
      },
      {
        "offset": 100,
        "color": "#4D3041"
      }
    ]
  },
  {
    "name": "broco",
    "category": "cyclic",
    "stops": [
      {
        "offset": 0,
        "color": "#372E38"
      },
      {
        "offset": 5.3,
        "color": "#353348"
      },
      {
        "offset": 10.5,
        "color": "#383F61"
      },
      {
        "offset": 15.8,
        "color": "#3F537B"
      },
      {
        "offset": 21.1,
        "color": "#506C94"
      },
      {
        "offset": 26.3,
        "color": "#6684A9"
      },
      {
        "offset": 31.6,
        "color": "#819DB9"
      },
      {
        "offset": 36.8,
        "color": "#9DB2C7"
      },
      {
        "offset": 42.1,
        "color": "#B7C5D0"
      },
      {
        "offset": 47.4,
        "color": "#CBD2CC"
      },
      {
        "offset": 52.6,
        "color": "#CED2BA"
      },
      {
        "offset": 57.9,
        "color": "#C4C49D"
      },
      {
        "offset": 63.2,
        "color": "#AEAE7F"
      },
      {
        "offset": 68.4,
        "color": "#979664"
      },
      {
        "offset": 73.7,
        "color": "#7B7B4B"
      },
      {
        "offset": 78.9,
        "color": "#666439"
      },
      {
        "offset": 84.2,
        "color": "#514D2C"
      },
      {
        "offset": 89.5,
        "color": "#433E28"
      },
      {
        "offset": 94.7,
        "color": "#3A332C"
      },
      {
        "offset": 100,
        "color": "#372E37"
      }
    ]
  },
  {
    "name": "corko",
    "category": "cyclic",
    "stops": [
      {
        "offset": 0,
        "color": "#3F3E39"
      },
      {
        "offset": 5.3,
        "color": "#3E3D46"
      },
      {
        "offset": 10.5,
        "color": "#3E435A"
      },
      {
        "offset": 15.8,
        "color": "#435273"
      },
      {
        "offset": 21.1,
        "color": "#50688E"
      },
      {
        "offset": 26.3,
        "color": "#647FA4"
      },
      {
        "offset": 31.6,
        "color": "#7B97B6"
      },
      {
        "offset": 36.8,
        "color": "#93ACC1"
      },
      {
        "offset": 42.1,
        "color": "#A6BEC7"
      },
      {
        "offset": 47.4,
        "color": "#B0C9C3"
      },
      {
        "offset": 52.6,
        "color": "#AAC9B2"
      },
      {
        "offset": 57.9,
        "color": "#98BF9A"
      },
      {
        "offset": 63.2,
        "color": "#81B080"
      },
      {
        "offset": 68.4,
        "color": "#6C9B66"
      },
      {
        "offset": 73.7,
        "color": "#59844A"
      },
      {
        "offset": 78.9,
        "color": "#4C6D37"
      },
      {
        "offset": 84.2,
        "color": "#455A2C"
      },
      {
        "offset": 89.5,
        "color": "#414D2C"
      },
      {
        "offset": 94.7,
        "color": "#404432"
      },
      {
        "offset": 100,
        "color": "#3F3E39"
      }
    ]
  },
  {
    "name": "viko",
    "category": "cyclic",
    "stops": [
      {
        "offset": 0,
        "color": "#4E193D"
      },
      {
        "offset": 5.3,
        "color": "#45224D"
      },
      {
        "offset": 10.5,
        "color": "#3A3365"
      },
      {
        "offset": 15.8,
        "color": "#33477A"
      },
      {
        "offset": 21.1,
        "color": "#386092"
      },
      {
        "offset": 26.3,
        "color": "#4B7AA5"
      },
      {
        "offset": 31.6,
        "color": "#6B97B7"
      },
      {
        "offset": 36.8,
        "color": "#8DADC4"
      },
      {
        "offset": 42.1,
        "color": "#B0BEC7"
      },
      {
        "offset": 47.4,
        "color": "#CCC1BE"
      },
      {
        "offset": 52.6,
        "color": "#D8B8A7"
      },
      {
        "offset": 57.9,
        "color": "#D8A588"
      },
      {
        "offset": 63.2,
        "color": "#CE8C6B"
      },
      {
        "offset": 68.4,
        "color": "#BF724C"
      },
      {
        "offset": 73.7,
        "color": "#A95332"
      },
      {
        "offset": 78.9,
        "color": "#8E3921"
      },
      {
        "offset": 84.2,
        "color": "#77221E"
      },
      {
        "offset": 89.5,
        "color": "#661822"
      },
      {
        "offset": 94.7,
        "color": "#59142D"
      },
      {
        "offset": 100,
        "color": "#50193B"
      }
    ]
  }
];

export function gradientCss(stops: Array<{ offset: number; color: string }>): string {
  return (
    "linear-gradient(to right, " +
    stops.map((s) => `${s.color} ${s.offset}%`).join(", ") +
    ")"
  );
}
