#!/usr/bin/env bash
# Generated by loc.sh installer (https://github.com/arturcarvalho/loc.sh).
# Counts lines of code in the current directory via cloc.
EXCLUDE_LANGS='Markdown,JSON,JSON5,YAML,TOML,INI,Bourne Shell,Bourne Again Shell,Korn Shell,zsh'
EXCLUDE_EXTS='png,jpg,jpeg,gif,svg,ico,webp,bmp,tiff,mp4,mov,mp3,wav,ogg,flac,m4a,pdf,woff,woff2,ttf,eot,otf,zip,gz,tar,7z,rar'
NOT_MATCH_F='package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock|Gemfile\.lock|poetry\.lock|composer\.lock|go\.sum'
EXCLUDE_DIRS='dist,examples,node_modules,scripts,.claude'

set -euo pipefail

if ! command -v cloc >/dev/null 2>&1; then
  printf "loc.sh needs 'cloc' but it is not installed.\nInstall on macOS: brew install cloc\n" >&2
  exit 127
fi

ARGS=()
[ -n "$EXCLUDE_LANGS" ] && ARGS+=("--exclude-lang=$EXCLUDE_LANGS")
[ -n "$EXCLUDE_EXTS"  ] && ARGS+=("--exclude-ext=$EXCLUDE_EXTS")

# Always self-exclude this script; merge in any user-chosen lock-file pattern.
SKIP_BASENAMES='loc\.sh'
[ -n "$NOT_MATCH_F" ] && SKIP_BASENAMES="$SKIP_BASENAMES|$NOT_MATCH_F"

if git rev-parse --git-dir >/dev/null 2>&1; then
  # Tracked + untracked-not-ignored files (so uncommitted work is counted but
  # .gitignore is respected). cloc's --not-match-f is ignored under
  # --list-file, so filter via grep instead.
  if [ -n "$EXCLUDE_DIRS" ]; then
    DIR_PATTERN=$(printf '%s' "$EXCLUDE_DIRS" | sed 's/\./\\./g; s/,/|/g')
    exec cloc "${ARGS[@]}" --list-file=<(
      git ls-files -co --exclude-standard \
        | grep -Ev "(^|/)($SKIP_BASENAMES)\$" \
        | grep -Ev "(^|/)($DIR_PATTERN)/"
    )
  else
    exec cloc "${ARGS[@]}" --list-file=<(
      git ls-files -co --exclude-standard | grep -Ev "(^|/)($SKIP_BASENAMES)\$"
    )
  fi
else
  ALL_EXCLUDE_DIRS="node_modules,vendor,dist,build,target,.venv,venv,.next,.nuxt,.cache,coverage,.git"
  [ -n "$EXCLUDE_DIRS" ] && ALL_EXCLUDE_DIRS="$ALL_EXCLUDE_DIRS,$EXCLUDE_DIRS"
  ARGS+=("--not-match-f=^($SKIP_BASENAMES)$")
  ARGS+=("--exclude-dir=$ALL_EXCLUDE_DIRS")
  exec cloc "${ARGS[@]}" .
fi
